import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy | Chess Mobile",
  description: "Privacy Policy for Chess Mobile.",
};

const sections = [
  {
    id: 1,
    title: "Scope",
    content: (
      <p>
        This policy applies to the use of Chess Mobile on iOS, Android, and any
        other platform on which the App may be available. It covers both guest
        use and use with an account signed in through external providers.
      </p>
    ),
  },
  {
    id: 2,
    title: "What data we process",
    content: (
      <>
        <h3>2.1 Account and identity data</h3>
        <p>
          If you choose to sign in with Apple or Google through Supabase, we
          may process:
        </p>
        <ul>
          <li>your name or display name provided by the provider;</li>
          <li>your email address, when shared by the provider;</li>
          <li>a unique user identifier from the authentication service;</li>
          <li>
            basic account metadata and technical data needed to keep your
            session active.
          </li>
        </ul>
        <p>
          If you use the App as a guest, we do not need to create an account
          for you to play locally.
        </p>

        <h3>2.2 Game data, progress, and preferences stored on your device</h3>
        <p>
          The App stores locally on your device data necessary to provide the
          gameplay experience, including:
        </p>
        <ul>
          <li>game history;</li>
          <li>puzzle progress and unlocked bots;</li>
          <li>daily streak;</li>
          <li>selected language;</li>
          <li>chosen visual theme, board, pieces, and sounds;</li>
          <li>sound, vibration, and other settings preferences;</li>
          <li>
            a flag to avoid repeatedly showing the request for an app rating;
          </li>
          <li>session tokens and authentication persistence when you sign in.</li>
        </ul>

        <h3>2.3 Data sent when you use online features</h3>
        <p>Some features require data exchange with external services:</p>
        <ul>
          <li>
            when you play against bots, the App sends the game position in FEN
            format and the selected level or Elo to the chess engine server to
            obtain the next move;
          </li>
          <li>
            when you open puzzles, the App requests chess puzzle content from
            the Lichess API;
          </li>
          <li>
            when you sign in, the App redirects and communicates data with
            Apple, Google, and Supabase to authenticate your account.
          </li>
        </ul>

        <h3>2.4 Technical data generated by external services</h3>
        <p>
          As is common with online services, providers involved in the
          functioning of the App may receive technical data such as IP address,
          request date and time, device type, operating system, browser or
          session information, and operational logs needed for security,
          diagnostics, or service delivery.
        </p>

        <h3>2.5 Data we do not currently request</h3>
        <p>Based on the App&apos;s current implementation, we do not request access to:</p>
        <ul>
          <li>camera;</li>
          <li>microphone;</li>
          <li>photos or gallery;</li>
          <li>contacts;</li>
          <li>precise location;</li>
          <li>advertising identifiers for cross-app tracking.</li>
        </ul>
      </>
    ),
  },
  {
    id: 3,
    title: "How we use data",
    content: (
      <>
        <p>We use the information above to:</p>
        <ul>
          <li>enable sign-in and session maintenance;</li>
          <li>save your progress, settings, and history;</li>
          <li>
            provide games against bots, puzzles, and other core features;
          </li>
          <li>display your profile and statistics within the App;</li>
          <li>improve stability, security, diagnostics, and support;</li>
          <li>
            comply with legal obligations and respond to valid requests from
            authorities when required;
          </li>
          <li>prevent abuse, misuse, or interference with the service.</li>
        </ul>
        <p>
          We do not sell your personal data and we do not use the App for
          behavioral advertising based on cross-app tracking.
        </p>
      </>
    ),
  },
  {
    id: 4,
    title: "Who we share information with",
    content: (
      <>
        <p>We may share information only to the extent necessary to operate the App:</p>
        <ul>
          <li>
            <strong>Supabase</strong>, for authentication, session management,
            and related account services;
          </li>
          <li>
            <strong>Apple and Google</strong>, when you choose to sign in with
            those providers;
          </li>
          <li>
            <strong>Lichess</strong>, to obtain chess puzzles through its API;
          </li>
          <li>
            <strong>Stockfish server infrastructure</strong> used to calculate
            bot moves;
          </li>
          <li>
            <strong>app stores and system services</strong>, for example when
            you choose to leave a review or use system mechanisms to share
            content.
          </li>
        </ul>
        <p>
          If you choose to share a game or recommend the App using the system
          share sheet, the information you choose to send will pass to the
          third-party app or service you select and will be subject to its own
          policies.
        </p>
      </>
    ),
  },
  {
    id: 5,
    title: "Legal bases where applicable",
    content: (
      <>
        <p>
          Where privacy laws require a specific legal basis, we process data on
          the following bases:
        </p>
        <ul>
          <li>
            performance of the service you request, for example to sign in,
            save progress, or play against bots;
          </li>
          <li>
            your consent, when you choose to use optional features such as
            signing in with an external provider;
          </li>
          <li>
            legitimate interest in maintaining security, preventing fraud,
            debugging errors, and operating the App;
          </li>
          <li>compliance with legal obligations.</li>
        </ul>
      </>
    ),
  },
  {
    id: 6,
    title: "Data retention",
    content: (
      <>
        <p>
          We retain data for as long as necessary for the purposes described in
          this policy:
        </p>
        <ul>
          <li>
            data stored locally remains on your device until you delete the
            App, clear its data, or the App overwrites it;
          </li>
          <li>
            account data managed through Supabase is retained while the account
            remains active or until you request deletion, unless we need to
            keep certain information for legal or security reasons;
          </li>
          <li>
            technical requests to the bot server and other external services
            may be temporarily recorded in operational logs for diagnostics,
            security, and service continuity;
          </li>
          <li>
            third parties involved in the service retain data in accordance
            with their own policies.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: 7,
    title: "Security",
    content: (
      <>
        <p>
          We apply reasonable measures to protect information processed by the
          App. However, no system is entirely fail-safe and we cannot guarantee
          absolute security.
        </p>
        <p>
          We recommend keeping your device protected, using secure access
          methods, and signing out if you share the device with others.
        </p>
      </>
    ),
  },
  {
    id: 8,
    title: "Your choices and rights",
    content: (
      <>
        <p>
          Depending on your jurisdiction, you may have the right to request
          access, correction, deletion, objection, restriction of processing,
          or portability of your data.
        </p>
        <p>You may also:</p>
        <ul>
          <li>use the App as a guest instead of signing in;</li>
          <li>sign out at any time;</li>
          <li>
            delete local data by uninstalling the App or clearing its data
            through the operating system;
          </li>
          <li>
            contact us to request deletion of account data or exercise privacy
            rights.
          </li>
        </ul>
        <p>
          For privacy requests, contact us at{" "}
          <a href="mailto:chess@americansolutionscenter.com">
            chess@americansolutionscenter.com
          </a>
          .
        </p>
      </>
    ),
  },
  {
    id: 9,
    title: "Children",
    content: (
      <p>
        The App is intended for a general audience and is not intentionally
        directed to children for the independent collection of personal data
        without adult involvement where required by law. If you believe that a
        child has improperly provided personal data to us, please write to us
        so we can review the matter and take reasonable steps as appropriate.
      </p>
    ),
  },
  {
    id: 10,
    title: "International transfers",
    content: (
      <p>
        Third-party services used by the App may operate in different
        countries. As a result, your information may be processed outside your
        place of residence, subject to the safeguards and practices of the
        relevant provider.
      </p>
    ),
  },
  {
    id: 11,
    title: "Third-party services",
    content: (
      <>
        <p>
          Some features depend on third parties. We recommend reviewing their
          policies as well, to the extent they apply to your use:
        </p>
        <ul>
          <li>
            Supabase:{" "}
            <a
              href="https://supabase.com"
              target="_blank"
              rel="noopener noreferrer"
            >
              supabase.com
            </a>
          </li>
          <li>
            Apple:{" "}
            <a
              href="https://www.apple.com/legal/privacy/"
              target="_blank"
              rel="noopener noreferrer"
            >
              apple.com/legal/privacy
            </a>
          </li>
          <li>
            Google:{" "}
            <a
              href="https://policies.google.com/privacy"
              target="_blank"
              rel="noopener noreferrer"
            >
              policies.google.com/privacy
            </a>
          </li>
          <li>
            Lichess:{" "}
            <a
              href="https://lichess.org/privacy"
              target="_blank"
              rel="noopener noreferrer"
            >
              lichess.org/privacy
            </a>
          </li>
        </ul>
      </>
    ),
  },
  {
    id: 12,
    title: "Changes to this policy",
    content: (
      <p>
        We may update this Privacy Policy to reflect changes in the App, in the
        providers we use, or in legal requirements. When we publish an updated
        version, we will change the effective date.
      </p>
    ),
  },
  {
    id: 13,
    title: "Contact",
    content: (
      <>
        <p>
          If you have questions about this Privacy Policy or about data
          processing in Chess Mobile, you may write to:
        </p>
        <p>
          <a href="mailto:chess@americansolutionscenter.com">
            chess@americansolutionscenter.com
          </a>
        </p>
      </>
    ),
  },
];

export default function ChessPrivacyPolicy() {
  return (
    <div className="min-h-screen bg-zinc-50 dark:bg-zinc-950">
      <main className="mx-auto max-w-3xl px-6 py-16 sm:px-10">
        {/* Header */}
        <header className="mb-12">
          <div className="mb-4 flex justify-end">
            <Link
              href="/chess/politica-de-privacidad"
              className="text-sm text-zinc-600 underline underline-offset-2 hover:text-zinc-800 dark:text-zinc-400 dark:hover:text-zinc-200"
            >
              Leer en español
            </Link>
          </div>
          <p className="mb-2 text-sm font-medium uppercase tracking-widest text-zinc-400 dark:text-zinc-500">
            Chess Mobile
          </p>
          <h1 className="text-3xl font-semibold tracking-tight text-zinc-900 dark:text-zinc-50 sm:text-4xl">
            Privacy Policy
          </h1>
          <p className="mt-3 text-sm text-zinc-500 dark:text-zinc-400">
            Effective date: March 21, 2026
          </p>
          <p className="mt-2 text-sm text-zinc-500 dark:text-zinc-400">
            This Privacy Policy describes how Chess Mobile (the &quot;App&quot;),
            operated by American Solutions Center (&quot;we,&quot; &quot;us,&quot;
            or &quot;our&quot;), collects, uses, shares, and protects
            information when you use the application.
          </p>
          <p className="mt-2 text-sm text-zinc-500 dark:text-zinc-400">
            Privacy contact:{" "}
            <a
              href="mailto:chess@americansolutionscenter.com"
              className="underline underline-offset-2"
            >
              chess@americansolutionscenter.com
            </a>
          </p>
          <p className="mt-2 text-sm text-zinc-400 dark:text-zinc-500 italic">
            This text was prepared taking into account the current behavior of
            version 1.0.0 of the App.
          </p>
        </header>

        {/* Sections */}
        <div className="space-y-10">
          {sections.map((section) => (
            <section key={section.id}>
              <h2 className="mb-3 text-lg font-semibold text-zinc-900 dark:text-zinc-50">
                {section.id}. {section.title}
              </h2>
              <div className="prose-policy">{section.content}</div>
            </section>
          ))}
        </div>

        <footer className="mt-14 border-t border-zinc-200 pt-8 text-sm text-zinc-600 dark:border-zinc-800 dark:text-zinc-400">
          <p className="mb-3 font-medium text-zinc-700 dark:text-zinc-300">
            Required links
          </p>
          <div className="flex flex-wrap gap-4">
            <Link
              href="/chess/politica-de-privacidad"
              className="underline underline-offset-2"
            >
              Política de Privacidad
            </Link>
            <Link
              href="/chess/terminos-y-condiciones"
              className="underline underline-offset-2"
            >
              Términos de Uso
            </Link>
            <Link
              href="/chess/privacy-policy"
              className="underline underline-offset-2"
            >
              Privacy Policy
            </Link>
            <Link href="/chess/terms" className="underline underline-offset-2">
              Terms of Use
            </Link>
          </div>
        </footer>
      </main>

      <style>{`
        .prose-policy p {
          color: rgb(82 82 91);
          line-height: 1.75;
          margin-bottom: 0.75rem;
        }
        .prose-policy ul {
          list-style-type: disc;
          padding-left: 1.5rem;
          margin-bottom: 0.75rem;
          color: rgb(82 82 91);
          line-height: 1.75;
        }
        .prose-policy li {
          margin-bottom: 0.25rem;
        }
        .prose-policy h3 {
          font-weight: 600;
          font-size: 0.9375rem;
          color: rgb(39 39 42);
          margin-top: 1.25rem;
          margin-bottom: 0.5rem;
        }
        .prose-policy code {
          font-size: 0.8125rem;
          background-color: rgb(244 244 245);
          padding: 0.125rem 0.375rem;
          border-radius: 0.25rem;
          color: rgb(39 39 42);
        }
        .prose-policy a {
          color: rgb(24 24 27);
          text-decoration: underline;
          text-underline-offset: 2px;
        }
        .prose-policy a:hover {
          color: rgb(82 82 91);
        }
        @media (prefers-color-scheme: dark) {
          .prose-policy p,
          .prose-policy ul {
            color: rgb(161 161 170);
          }
          .prose-policy h3 {
            color: rgb(212 212 216);
          }
          .prose-policy code {
            background-color: rgb(39 39 42);
            color: rgb(212 212 216);
          }
          .prose-policy a {
            color: rgb(212 212 216);
          }
          .prose-policy a:hover {
            color: rgb(161 161 170);
          }
        }
      `}</style>
    </div>
  );
}
